### ISSUE TITLE
Does not work for multiple players

### ISSUE THREAD

**Issue by Unrud** [hugosenari/mpris2#3]
``` python
from mpris2 import Player
p1 = Player(dbus_interface_info={'dbus_uri': "org.mpris.MediaPlayer2.parole"})
p2 = Player(dbus_interface_info={'dbus_uri': "org.mpris.MediaPlayer2.clementine"})
p2.PlayPause() # controls parole not clementine
```

Problem:

``` python
class Player(Interfaces):
    @DbusInterface(Interfaces.PLAYER, Interfaces.OBJECT_PATH)
    def __init__(self):
        pass
    @DbusMethod
    def PlayPause(self):
        pass
```

`DbusInterface` and `DbusMethod` are only called once when the class object is created and the same instances of `DbusInterface` and `DbusMethod` are used for all instances of `Player`.

**Comment by hugosenari** [comment]
Thank you, I never tested this case before.

I created a branch to fix this issue, can you say if this resolve your problem?

Tested here with vlc and gmusicbrowser.

**Comment by Unrud** [comment]
It works, thank you.
