### ISSUE TITLE
Typo in Volume?

### ISSUE THREAD

**Issue by sedrubal** [hugosenari/mpris2#5]
I'm expecting strange errors with the type [Volume](https://github.com/hugosenari/mpris2/blob/master/mpris2/types/volume.py#L27):

``` python
AttributeError: 'Volume' object has no attribute '_time'
```

Is it possible that `_time` (in [`line 27`](https://github.com/hugosenari/mpris2/blob/master/mpris2/types/volume.py#L27) and [`line 30`](https://github.com/hugosenari/mpris2/blob/master/mpris2/types/volume.py#L30)) is a type/copy paste error and it should be `_volume`?

**Comment by hugosenari** [comment]
Hi, thank you!

**Comment by sedrubal** [comment]
Thanks. Can you release this on pypi?

**Comment by hugosenari** [comment]
Done 1.0.2

**Comment by sedrubal** [comment]
Nice, thanks ;)
